Repository EscanBE/evermint, pull requests merged in 2024-03, with the labels that each got.

#108 fix: resolve compile error `*_test.go` after run rename chain
  CHANGELOG.md
  rename_chain/main.go
Labels: enhancement

#109 fix: resolve compile error `*_test.go` after run rename chain (backport #108)
  CHANGELOG.md
  rename_chain/main.go
Labels: enhancement, backport

#110 fix(ante): reject EVM txs which having negative value
  CHANGELOG.md
  app/ante/evm/eth.go
  app/ante/evm/eth_test.go
  app/ante/handler_options.go
Labels: enhancement

#112 imp: add some validation relates to number range for EVM txs
  CHANGELOG.md
  app/ante/evm/eth.go
  app/ante/evm/eth_test.go
Labels: enhancement

#113 imp: add some validation relates to number range for EVM txs (backport #112)
  CHANGELOG.md
  app/ante/evm/eth.go
  app/ante/evm/eth_test.go
Labels: enhancement, backport

#114 deps: bump cosmos-sdk v0.47.10
  CHANGELOG.md
  go.mod
  go.sum
Labels: dependency

#115 chores: prepare release v12.2.5
  CHANGELOG.md
Labels: release
